// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ScrollLockController from "../ScrollLockController.mjs";

import './style.css';
;

function enableLockButton(lockButtonEl) {
  var onLockButtonClick = function (param) {
    return ScrollLockController.lock(undefined);
  };
  lockButtonEl.addEventListener("click", onLockButtonClick);
  
}

function enableUnlockButton(unlockButtonEl) {
  var onUnlockButtonClick = function (param) {
    return ScrollLockController.unlock(undefined);
  };
  unlockButtonEl.addEventListener("click", onUnlockButtonClick);
  
}

var lockButtonEl = document.querySelector(".js-lock-button");

if (!(lockButtonEl == null)) {
  enableLockButton(lockButtonEl);
}

var unlockButtonEl = document.querySelector(".js-unlock-button");

if (!(unlockButtonEl == null)) {
  enableUnlockButton(unlockButtonEl);
}

export {
  enableLockButton ,
  enableUnlockButton ,
  
}
/*  Not a pure module */
