// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Manager$Scrollock from "../Manager.bs.js";
import * as ReservedGapPlugin$Scrollock from "../ReservedGapPlugin.bs.js";
import * as Scrollok__Helpers$Scrollock from "../Scrollok__Helpers.bs.js";

import './style.css';
;

var scrollok = Manager$Scrollock.make([(function (param) {
          return ReservedGapPlugin$Scrollock.make(undefined, param);
        })], undefined);

function enableLockButton(lockButtonEl) {
  var scrollableNodeList = document.querySelectorAll(".js-modal-with-scroll");
  var onLockButtonClick = function (param) {
    scrollableNodeList.forEach(function (scrollableNode, _idx) {
          var scrollableEl = Scrollok__Helpers$Scrollock.convertNodeToElement(scrollableNode);
          if (scrollableEl !== undefined) {
            return Manager$Scrollock.lock(scrollok, [Caml_option.valFromOption(scrollableEl)]);
          }
          
        });
    
  };
  lockButtonEl.addEventListener("click", onLockButtonClick);
  
}

function enableUnlockButton(unlockButtonEl) {
  var scrollableNodeList = document.querySelectorAll(".js-modal-with-scroll");
  var onUnlockButtonClick = function (param) {
    scrollableNodeList.forEach(function (scrollableNode, _idx) {
          var scrollableEl = Scrollok__Helpers$Scrollock.convertNodeToElement(scrollableNode);
          if (scrollableEl !== undefined) {
            return Manager$Scrollock.unlock(scrollok, [Caml_option.valFromOption(scrollableEl)]);
          }
          
        });
    
  };
  unlockButtonEl.addEventListener("click", onUnlockButtonClick);
  
}

var __x = document;

var lockButtonEl = __x.querySelector(".js-lock-button");

if (!(lockButtonEl == null)) {
  enableLockButton(lockButtonEl);
}

var __x$1 = document;

var unlockButtonEl = __x$1.querySelector(".js-unlock-button");

if (!(unlockButtonEl == null)) {
  enableUnlockButton(unlockButtonEl);
}

export {
  scrollok ,
  enableLockButton ,
  enableUnlockButton ,
  
}
/*  Not a pure module */
