version: '2.4'

services:
  lib:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/prebuild/Dockerfile
      target: dependencies
      args:
        devmode: 1
    working_dir: /opt/app/
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
    user: node
    volumes:
      - ${PWD}:/opt/app/:delegated
      - /opt/app/node_modules/
      # Add .wallaby folder from home for licensing and wallaby update files
      - ~/.wallaby:/home/node/.wallaby
      - ~/.quokka:/home/node/.quokka
