// Generated by ReScript, PLEASE EDIT WITH CARE


import './style.css';
;

var appEl = document.querySelector("#app");

if (!(appEl == null)) {
  appEl.innerHTML = "\n    <h1>Hello Vite!</h1>\n    <a href=\"https://vitejs.dev/guide/features.html\" target=\"_blank\">Documentation</a>\n  ";
}

export {
  
}
/*  Not a pure module */
