// Generated by ReScript, PLEASE EDIT WITH CARE


import './style.css'

document.querySelector('#app').innerHTML = `
  <h1>Hello Vite!</h1>
  <a href="https://vitejs.dev/guide/features.html" target="_blank">Documentation</a>
`
;

export {
  
}
/*  Not a pure module */
