// Generated by ReScript, PLEASE EDIT WITH CARE


function lock(param) {
  console.log("lock");
  
}

function unlock(param) {
  console.log("unlock");
  
}

export {
  lock ,
  unlock ,
  
}
/* No side effect */
