// Generated by ReScript, PLEASE EDIT WITH CARE


function make(param) {
  return function (param) {
    return {
            onBodyScrollLock: (function (param) {
                console.log("lock");
                
              }),
            onBodyScrollUnlock: (function (param) {
                console.log("unlock");
                
              }),
            onLockTargetsAdd: undefined,
            onLockTargetsRemove: undefined
          };
  };
}

export {
  make ,
  
}
/* No side effect */
