// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as BodyScrollLock from "body-scroll-lock";
import * as ScrollLockController_Helpers$ScrollLockController from "./ScrollLockController_Helpers.bs.js";

function make(onBodyScrollLock, onBodyScrollUnlock, param) {
  var locks = ScrollLockController_Helpers$ScrollLockController.LocksSet.make(undefined);
  var isLocked = ScrollLockController_Helpers$ScrollLockController.TrackedValue.make((function (newIsLocked) {
          if (newIsLocked) {
            if (onBodyScrollLock !== undefined) {
              return Curry._1(onBodyScrollLock, undefined);
            } else {
              return ;
            }
          } else if (onBodyScrollUnlock !== undefined) {
            return Curry._1(onBodyScrollUnlock, undefined);
          } else {
            return ;
          }
        }), false);
  return {
          locks: locks,
          isLocked: isLocked
        };
}

function isBodyScrollLocked(it) {
  return !ScrollLockController_Helpers$ScrollLockController.LocksSet.isEmpty(it.locks);
}

function lock(it, targetElements) {
  var added = ScrollLockController_Helpers$ScrollLockController.LocksSet.add(it.locks, targetElements);
  added.forEach(function (targetElement) {
        BodyScrollLock.disableBodyScroll(targetElement, {
              reserveScrollBarGap: true
            });
        
      });
  return ScrollLockController_Helpers$ScrollLockController.TrackedValue.set(it.isLocked, (function (param) {
                return isBodyScrollLocked(it);
              }));
}

function unlock(it, targetElements) {
  var removed = ScrollLockController_Helpers$ScrollLockController.LocksSet.remove(it.locks, targetElements);
  removed.forEach(function (targetElement) {
        BodyScrollLock.enableBodyScroll(targetElement);
        
      });
  return ScrollLockController_Helpers$ScrollLockController.TrackedValue.set(it.isLocked, (function (param) {
                return isBodyScrollLocked(it);
              }));
}

export {
  make ,
  lock ,
  unlock ,
  
}
/* body-scroll-lock Not a pure module */
