// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var isServer = Js_types.test(window, /* Undefined */0);

var uniq = ((array) => [...new Set(array)]);

function isEmptyArray(array) {
  return array.length === 0;
}

function make(param) {
  return {
          contents: []
        };
}

function isEmpty(it) {
  return it.contents.length === 0;
}

function isExistingLock(it, lock) {
  return it.contents.some(function (entityLock) {
              return entityLock === lock;
            });
}

function add(it, locks) {
  var uniqLocks = uniq(locks);
  var added = uniqLocks.filter(function (lock) {
        return !isExistingLock(it, lock);
      });
  it.contents = it.contents.concat(added);
  return added;
}

function remove(it, locks) {
  var removingLocksRef = {
    contents: uniq(locks)
  };
  var removedRef = {
    contents: []
  };
  it.contents = it.contents.filter(function (existingLock) {
        var removingLockIdx = removingLocksRef.contents.indexOf(existingLock);
        var isRemovingLock = removingLockIdx >= 0;
        var removedLocks = removingLocksRef.contents.splice(removingLockIdx, 1);
        removedRef.contents = removedRef.contents.concat(removedLocks);
        return !isRemovingLock;
      });
  return removedRef.contents;
}

var LocksSet = {
  make: make,
  isEmpty: isEmpty,
  isExistingLock: isExistingLock,
  add: add,
  remove: remove
};

function make$1(onChage, defaultValue) {
  return {
          valueRef: {
            contents: defaultValue
          },
          onChange: onChage
        };
}

function set(it, valueGetter) {
  var prevValue = it.valueRef.contents;
  var newValue = valueGetter(prevValue);
  if (newValue !== prevValue) {
    it.valueRef.contents = newValue;
    return Curry._1(it.onChange, newValue);
  }
  
}

function get(it) {
  return it.valueRef.contents;
}

var TrackedValue = {
  make: make$1,
  set: set,
  get: get
};

var checkIsElementNode = ((node) => node instanceof Element);

function convertNodeToElement(node) {
  if (checkIsElementNode(node)) {
    return Caml_option.some(node);
  }
  
}

export {
  isServer ,
  uniq ,
  isEmptyArray ,
  LocksSet ,
  TrackedValue ,
  checkIsElementNode ,
  convertNodeToElement ,
  
}
/* isServer Not a pure module */
