// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BodyScrollLock from "body-scroll-lock";

function make(param) {
  return {
          contents: []
        };
}

function isEmpty(value) {
  return value.contents.length === 0;
}

function add(value, lock) {
  value.contents = value.contents.concat([lock]);
  
}

function remove(value, lock) {
  value.contents = value.contents.filter(function (existingLock) {
        return existingLock !== lock;
      });
  
}

var LocksSet = {
  make: make,
  isEmpty: isEmpty,
  add: add,
  remove: remove
};

function make$1(param) {
  return {
          locks: {
            contents: []
          }
        };
}

function lock(value, targetElement) {
  add(value.locks, targetElement);
  BodyScrollLock.disableBodyScroll(targetElement, {
        reserveScrollBarGap: true
      });
  
}

function unlock(value, targetElement) {
  remove(value.locks, targetElement);
  BodyScrollLock.enableBodyScroll(targetElement);
  
}

export {
  LocksSet ,
  make$1 as make,
  lock ,
  unlock ,
  
}
/* body-scroll-lock Not a pure module */
