// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var isServer = Js_types.test(window, /* Undefined */0);

var Environment = {
  isServer: isServer
};

function create(onChage, defaultValue) {
  var valueRef = {
    contents: defaultValue
  };
  var setValue = function (options, valueGetter) {
    var prevValue = valueRef.contents;
    var newValue = valueGetter(prevValue);
    var isValueChanged = newValue !== prevValue;
    if (isValueChanged) {
      valueRef.contents = newValue;
      if (options !== undefined && options.silent === true) {
        return onChage(newValue);
      } else {
        return ;
      }
    }
    
  };
  var getValue = function (param) {
    return valueRef.contents;
  };
  return {
          getValue: getValue,
          setValue: setValue
        };
}

var TrackedValue = {
  create: create
};

var checkIsElementNode = ((node) => node instanceof Element);

function convertNodeToElement(node) {
  if (checkIsElementNode(node)) {
    return Caml_option.some(node);
  }
  
}

export {
  Environment ,
  TrackedValue ,
  checkIsElementNode ,
  convertNodeToElement ,
  
}
/* isServer Not a pure module */
