// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var uniq = ((array) => [...new Set(array)]);

function isEmptyArray(array) {
  return array.length === 0;
}

var isServer = Js_types.test(window, /* Undefined */0);

var checkIsElementNode = ((node) => node instanceof Element);

function convertNodeToElement(node) {
  if (checkIsElementNode(node)) {
    return Caml_option.some(node);
  }
  
}

export {
  uniq ,
  isEmptyArray ,
  isServer ,
  checkIsElementNode ,
  convertNodeToElement ,
  
}
/* isServer Not a pure module */
