// Generated by ReScript, PLEASE EDIT WITH CARE


var isServer = (typeof window === undefined);

function create(onChage, defaultValue) {
  var valueRef = {
    contents: defaultValue
  };
  var setValue = function (options, valueGetter) {
    var prevValue = valueRef.contents;
    var newValue = valueGetter(prevValue);
    var isValueChanged = newValue !== prevValue;
    if (isValueChanged) {
      valueRef.contents = newValue;
      if (options !== undefined && options.silent === true) {
        return onChage(newValue);
      } else {
        return ;
      }
    }
    
  };
  var getValue = function (param) {
    return valueRef.contents;
  };
  return {
          getValue: getValue,
          setValue: setValue
        };
}

var TrackedValue = {
  create: create
};

export {
  isServer ,
  TrackedValue ,
  
}
/* isServer Not a pure module */
