// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Js_types from "rescript/lib/es6/js_types.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var isServer = Js_types.test(window, /* Undefined */0);

var Environment = {
  isServer: isServer
};

function make(param) {
  return {
          contents: []
        };
}

function add(entity, lock) {
  entity.contents = entity.contents.concat([lock]);
  
}

function remove(entity, lock) {
  entity.contents = entity.contents.filter(function (existingLock) {
        return existingLock !== lock;
      });
  
}

var LocksSet = {
  make: make,
  add: add,
  remove: remove
};

function make$1(onChage, defaultValue) {
  return {
          valueRef: {
            contents: defaultValue
          },
          onChange: onChage
        };
}

function set(entity, valueGetter) {
  var prevValue = entity.valueRef.contents;
  var newValue = valueGetter(prevValue);
  if (newValue !== prevValue) {
    entity.valueRef.contents = newValue;
    return Curry._1(entity.onChange, newValue);
  }
  
}

function get(entity) {
  return entity.valueRef.contents;
}

var TrackedValue = {
  make: make$1,
  set: set,
  get: get
};

var checkIsElementNode = ((node) => node instanceof Element);

function convertNodeToElement(node) {
  if (checkIsElementNode(node)) {
    return Caml_option.some(node);
  }
  
}

export {
  Environment ,
  LocksSet ,
  TrackedValue ,
  checkIsElementNode ,
  convertNodeToElement ,
  
}
/* isServer Not a pure module */
